# Compiler and compiler flags
CXX = g++
CXXFLAGS = -Wall

# Directories
SRC_DIR = .
LIB_DIR = libraries
SQL_DIR = $(LIB_DIR)/sql
OPNSSL_DIR = $(LIB_DIR)/openssl

ifeq ($(OS),Windows_NT)
	LIBS = -L$(SQL_DIR) -L$(OPNSSL_DIR) -L$(CLIP_DIR) -static -lsqlite3 -lcrypt32 -lssl -lcrypto -lws2_32
else
	LIBS = -lsqlite3 -L/usr/lib -lssl -lcrypto
endif

# Source files
SRC = $(SRC_DIR)/main.cpp

# Target file
TARGET = simplePassMan

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -I$(SQL_DIR) -o $@ $^ $(LIBS)

clean:
	rm -f $(TARGET)
